{
archive_url: "https://api.github.com/repos/twbs/bootstrap/{archive_format}{/ref}"
archived: false
assignees_url: "https://api.github.com/repos/twbs/bootstrap/assignees{/user}"
blobs_url: "https://api.github.com/repos/twbs/bootstrap/git/blobs{/sha}"
branches_url: "https://api.github.com/repos/twbs/bootstrap/branches{/branch}"
clone_url: "https://github.com/twbs/bootstrap.git"
collaborators_url: "https://api.github.com/repos/twbs/bootstrap/collaborators{/collaborator}"
comments_url: "https://api.github.com/repos/twbs/bootstrap/comments{/number}"
commits_url: "https://api.github.com/repos/twbs/bootstrap/commits{/sha}"
compare_url: "https://api.github.com/repos/twbs/bootstrap/compare/{base}...{head}"
contents_url: "https://api.github.com/repos/twbs/bootstrap/contents/{+path}"
contributors_url: "https://api.github.com/repos/twbs/bootstrap/contributors"
created_at: "2011-07-29T21:19:00Z"
default_branch: "master"
deployments_url: "https://api.github.com/repos/twbs/bootstrap/deployments"
description: "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web."
disabled: false
downloads_url: "https://api.github.com/repos/twbs/bootstrap/downloads"
events_url: "https://api.github.com/repos/twbs/bootstrap/events"
fork: false
forks: 66575
forks_count: 66575
forks_url: "https://api.github.com/repos/twbs/bootstrap/forks"
full_name: "twbs/bootstrap"
git_commits_url: "https://api.github.com/repos/twbs/bootstrap/git/commits{/sha}"
git_refs_url: "https://api.github.com/repos/twbs/bootstrap/git/refs{/sha}"
git_tags_url: "https://api.github.com/repos/twbs/bootstrap/git/tags{/sha}"
git_url: "git://github.com/twbs/bootstrap.git"
has_downloads: true
has_issues: true
has_pages: true
has_projects: true
has_wiki: false
homepage: "https://getbootstrap.com"
hooks_url: "https://api.github.com/repos/twbs/bootstrap/hooks"
html_url: "https://github.com/twbs/bootstrap"
id: 2126244
issue_comment_url: "https://api.github.com/repos/twbs/bootstrap/issues/comments{/number}"
issue_events_url: "https://api.github.com/repos/twbs/bootstrap/issues/events{/number}"
issues_url: "https://api.github.com/repos/twbs/bootstrap/issues{/number}"
keys_url: "https://api.github.com/repos/twbs/bootstrap/keys{/key_id}"
labels_url: "https://api.github.com/repos/twbs/bootstrap/labels{/name}"
language: "JavaScript"
languages_url: "https://api.github.com/repos/twbs/bootstrap/languages"
license: {key: "mit", name: "MIT License", spdx_id: "MIT", url: "https://api.github.com/licenses/mit", node_id: "MDc6TGljZW5zZTEz"}
merges_url: "https://api.github.com/repos/twbs/bootstrap/merges"
milestones_url: "https://api.github.com/repos/twbs/bootstrap/milestones{/number}"
mirror_url: null
name: "bootstrap"
node_id: "MDEwOlJlcG9zaXRvcnkyMTI2MjQ0"
notifications_url: "https://api.github.com/repos/twbs/bootstrap/notifications{?since,all,participating}"
open_issues: 356
open_issues_count: 356
owner: {login: "twbs", id: 2918581, node_id: "MDEyOk9yZ2FuaXphdGlvbjI5MTg1ODE=", avatar_url: "https://avatars0.githubusercontent.com/u/2918581?v=4", gravatar_id: "", …}
private: false
pulls_url: "https://api.github.com/repos/twbs/bootstrap/pulls{/number}"
pushed_at: "2019-08-17T16:43:17Z"
releases_url: "https://api.github.com/repos/twbs/bootstrap/releases{/id}"
score: 1
size: 145765
ssh_url: "git@github.com:twbs/bootstrap.git"
stargazers_count: 135270
stargazers_url: "https://api.github.com/repos/twbs/bootstrap/stargazers"
statuses_url: "https://api.github.com/repos/twbs/bootstrap/statuses/{sha}"
subscribers_url: "https://api.github.com/repos/twbs/bootstrap/subscribers"
subscription_url: "https://api.github.com/repos/twbs/bootstrap/subscription"
svn_url: "https://github.com/twbs/bootstrap"
tags_url: "https://api.github.com/repos/twbs/bootstrap/tags"
teams_url: "https://api.github.com/repos/twbs/bootstrap/teams"
trees_url: "https://api.github.com/repos/twbs/bootstrap/git/trees{/sha}"
updated_at: "2019-08-17T16:34:50Z"
url: "https://api.github.com/repos/twbs/bootstrap"
watchers: 135270
watchers_count: 135270
}
